### ISSUE TITLE
Some difficulties with uploading s3->s3

### ISSUE THREAD

**Issue by hitz** [StanfordBioinformatics/encode_utils#10]
I was having some problems with eu_register.py when uploading files from an s3 bucket to a test bucket (test.encodedcc.org).  They seemed to be permission related.

I circumvented them by using boto3 instead of shell `aws s3 cp...`.   But I think this only works because I personally have special R/W access to those buckets as configured in my .boto.

**Comment by hitz** [comment]
See boto_copy branch

**Comment by nathankw** [comment]
Seems that aws cli or boto should be fine, what the issue comes down to I think is bucket policies. Here's how I think it may work:

The user running encode_utils has their own AWS credentials for `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` exported in their environment. When ``Connection.upload_file()`` sees that it has to do an S3 to S3 copy on a file, it grants the `federated_user_arn` (returned by the uploaded credentials JSON from the Portal) read and copy access on the S3 file in question.  This may be the only step to implement in order for this to work. Then, the rest of the method continues normally by kicking off a subprocess to upload the file using the `aws cli` or boto while exporting the AWS credentials given by the Portal in the subprocess.

**Comment by nathankw** [comment]
In progress. I wrote a [[wiki page|https://github.com/StanfordBioinformatics/encode_utils/wiki/could-to-cloud-file-transfers]] detailing how to address this on the server side am working together with Casey on this.

**Comment by nathankw** [comment]
Closing; details for S3 to S3 are in the wiki page linked above.
