### ISSUE TITLE
local variable 'response_json' referenced before assignment

### ISSUE THREAD

**Issue by yunhailuo** [StanfordBioinformatics/encode_utils#18]
When POST fails [here](https://github.com/StanfordBioinformatics/encode_utils/blob/master/encode_utils/connection.py#L1288-L1294), `response_json` won't be assigned and even `response.json` may not be valid. This leads to an error [here](https://github.com/StanfordBioinformatics/encode_utils/blob/36c527fefb36576e2f1a2b43e86d648cf4405b07/encode_utils/connection.py#L1303). Not sure what was intended here: `response.content` or `response.text` or others?

https://github.com/StanfordBioinformatics/encode_utils/blob/36c527fefb36576e2f1a2b43e86d648cf4405b07/encode_utils/connection.py#L1303

**Comment by nathankw** [comment]
That's a recent bug I introduced.  Will fix today, thanks for reporting.

**Comment by nathankw** [comment]
Fixed in master. I moved line 1295 ``response_json = response.json()`` up one line above the if block. 
In some cases of an error response, I noticed that the server doesn't always return JSON, which if I come across again will report for fixing on the server side. But the end point we are dealing with appears to return JSON just fine in error circumstances.
