### ISSUE TITLE
Bug to fix: strand-specificity handling is problematic

### ISSUE THREAD

**Issue by twang15** [StanfordBioinformatics/encode_utils#41]
Previously, strand specificity is not required.
However, ENCODE now changes this standard.
Whenever an experiment is submitted, may it be ChIP-seq or RNA-seq (single nuclear/multiome/bulk/standalone, etc), strand_specificity must be specified as one of [unstranded, forward, reverse]

Please see https://www.encodeproject.org/profiles/library for more details

### ENCODE Json scheme for strand_specificity
{
    "title": "Strand specificity",
    "description": "The strandedness of the library, forward or reverse resulting from a strand-specific protocol or unstranded.",
    "type": "string",
    "oneOf": [
        {
            "enum": [
                "forward",
                "reverse",
                "unstranded"
            ]
        },
        {
            "comment": "Libraries that have indicated specificity in the past, not for new submissions.",
            "permissions": "import_items",
            "enum": [
                "strand-specific"
            ]
        }
    ]
}

**Comment by paul-sud** [comment]
Hello,

You are correct that strand specificity is now required upon data submission to the ENCODE portal. However this is not an issue for `encode_utils` since it does not perform its own schema validation. However you are submitting the libraries you will need to include this property in order to be able to post them. For `eu_register.py` you can add a column to your input table, or if you are using the Python API you can add it the property to the dict before POSTing.

Please reach out to the ENCODE wrangling team if you need help determining the appropriate strand specificity for your libraries or need general help with submissions.

Best,

Paul

**Comment by twang15** [comment]
Yes, I have scheduled a zoom meeting with ENCODE team.

**Comment by paul-sud** [comment]
Great, I will close this ticket then. Feel free to reopen or create a new issue if you have further questions about `encode_utils`.
